Bugfix to allow to give a single column number to read from there to …
MetClassNet/MetClassNetR pull request #21
Opened 2022-04-27 14:23 UTC by elvanov

Hello,

This is the bug fix about the misplaced parenthesis that made the option of giving a single number to read the features from that column impossible.

Best,
Elva

2022-06-13 12:00 UTC, LiesaSalzer requested changes
Maybe we should remove the redundant descriptions from the functions and keep everything in the coding style suggested by BioC (e.g. using @return instead of the OUTPUT) 
And I had some remarks about the changes from the initial vignette

But I think we are almost done :)

2022-07-20 08:18 UTC, elvanov commented on DESCRIPTION
> +    MetNet (>= 1.11.4),
I fixed it, thanks for the remark!

2022-07-20 08:18 UTC, elvanov commented on DESCRIPTION
> +    MetNet,
You are right!

2022-07-20 08:18 UTC, elvanov commented on R/MultiLayerFunctions.R
> +# INPUTS:
You are right, I removed it to avoid redundancy.

2022-07-20 08:19 UTC, elvanov commented on R/MultiLayerFunctions.R
> +# OUTPUT: named list containing all the data (peakList, spectra,
Fixed

2022-07-20 08:19 UTC, elvanov commented on R/MultiLayerFunctions.R
> +# INPUTS:
Done

2022-07-20 08:19 UTC, elvanov commented on R/MultiLayerFunctions.R
> +#  inputData - list returned by the loadInputData function
Done

2022-07-20 08:19 UTC, elvanov commented on R/MultiLayerFunctions.R
> +# INPUTS:
Done

2022-07-20 08:19 UTC, elvanov commented on R/MultiLayerFunctions.R
> +# INPUTS:
Done

2022-07-20 08:19 UTC, elvanov commented on R/MultiLayerFunctions.R
> +# INPUTS:
Done

2022-07-20 08:40 UTC, elvanov commented on vignettes/MTBLS1586.Rmd
> +mtbls1586_qf_neg <- readMaf(file(neg_maf), ecol = 23, name = "mtbls1586_neg")
No, not needed. Check readMaf function, where "fnames" gets its value

2022-07-20 08:43 UTC, merged